Netflix/x-element

- mixins/lit-html-mixin.js
https://lit-html.polymer-project.org/guide/creating-directives
Also refer to https://github.com/Polymer/lit-html/issues/877 for how directive can be used to manage uncontrolled input elements
> allow creating custom directives

- x-element.js
> Fix JSDocs for “listen” and “unlisten”.

- README.md
The world needs to know!
@theengineear what do you think? Did I miss anything? It was certainly cathartic to scroll down the file and document the high level stuff. Later I would help to blow out details of the functionality
> useful readme origins

- package.json
> Publishes tests and demos

- test/test-analysis-errors.js
- test/test-basic-properties.js
- x-element.js
> Allow typeless props to be synced from attributes.

- .eslintrc.js
- package.json
- x-element.js
- yarn.lock
The “Class Fields” proposal has been adopted as part of ECMAScript 2022
and tests pass leveraging this feature in Chrome, Firefox, and Safari.
Closes #63.
> Leverage class fields and private class fields.

- demo/performance/index.html
- demo/performance/index.js
- test/test-template-engine.js
- x-element.js
Just a few changes to improve the performance of going from a user-defined template function to a clonable template element.
> Improve performance of injection phase.

- .github/workflows/push.yml
- .github/workflows/release.yml
- package.json
- yarn.lock
Just doing some periodic updates to the dependencies here to keep things fresh. Things seem to run fine with the new updates.
Note that the versions of node need to also be bumped in our GitHub actions files.
> Bump dev dependencies.

- package.json
- yarn.lock
Aiming to address:
* https://github.com/Netflix/x-element/security/dependabot/16
> Updates dev dependencies

- demo/lit-html/index.html
- demo/react/index.html
- demo/uhtml/index.html
- index.html
- package.json
Serves the root directory; now uses `<meta>` refresh to determine which page to start with
> Fixes server pathing

- eslint.config.js
- package-lock.json
- package.json
- x-element.js
One new violation:
```
~/x-element.js
1328:53  warning  Function declared in a loop contains unsafe references to variable(s) 'node'  no-loop-func
✖ 1 problem (0 errors, 1 warning)
```
> Adopts shared linter rules

- x-element.js
Nearly all of the template engine details are kept internal — this allowed us to ship a first pass of the code without needed high-levels of scrutiny. However, we can (and will!) revisit this internal code to make it more readable / self-documenting.
Closes #187.
> Improve internal “template engine”.

- CHANGELOG.md
Just minor formatting and marking our changes as “released”.
> Update “CHANGELOG.md” for forthcoming release.

- demo/performance/common.js
- demo/performance/default.html
- demo/performance/default.js
- demo/performance/index.css
- demo/performance/index.html
- demo/performance/index.js
- demo/performance/lit-html.html
- demo/performance/lit-html.js
- demo/performance/react.html
- demo/performance/react.js
- demo/performance/uhtml.html
- demo/performance/uhtml.js
- doc/PERFORMANCE.md
There is still a fair amount of work to be done before we can be super confident in the results here, but this feels like a good step forward:
* Tests all run in an iframe.
* Progress bar is printed to improve feedback.
* Long text moved to “PERFORMANCE.md”.
> Improve our performance demo.

- package-lock.json
- package.json
- test/x-test.js
Does the thing where we stop loading `x-test` from `unpkg.com`
> Reworks dependency on x-test

- README.md
Captures a sentiment from discussion
> Update README.md philosophy

- README.md
Installation steps must evolve with the introduction of `x-template.js` and `x-parser.js`
> Update README.md installation steps

- package-lock.json
- package.json
Just fixing some vulnerability warnings coming from npm.
> Bump dev dependencies to fix npm warnings.

- doc/TEMPLATES.md
Removing superfluous parts of the example code — expands on #292
> Simplify map example

- x-template.js
Refactored DOM-clearing logic to use modern, batch-optimized APIs for improved performance and readability.
1. **`removeChild` loop → `replaceChildren()`**
- Replaces manual reverse iteration with the spec’s optimized “replace all” algorithm.
- **Benefits:**
- **Fewer mutations:** Single `childList` record instead of N per child.
- **Better performance:** Allows browsers to batch DOM operations internally.
- **Clearer intent:** Reads as “replace all children” without manual index handling.
2. **`while(...).remove()` → `Range.deleteContents()`**
- Replaces sibling-by-sibling removal with a single range deletion.
- **Benefits:**
- **Bulk removal in one operation:** Reduces DOM tree surgery and mutation observer churn.
- **Optimized in all major engines:** Common internal path used by …
> Optimize DOM cleanup with replaceChildren() and Range.deleteContents()
