Netflix/x-element

- test/test-analysis-errors.js
- x-element.js
We previously passed an Error into the console.warn call. However, the
stack trace isn’t actually helpful. Instead, we’ll just pass the error
message.
Closes #71
> Shorten warning messages.

- test/test-analysis-errors.js
- test/test-attribute-changed-errors.js
- test/test-basic-properties.js
- test/test-initialization-errors.js
- test/test-internal-properties.js
- test/test-read-only-properties.js
- x-element.js
Previously, to help developers, we threw errors when trying to set/get
attributes/properties for “internal” properties. Instead of shouting
about internals, we’re going to take a new tact — silence.
Setting/getting property values for internals will now _do nothing_.
This has the excellent side-effect of freeing up internal properties to
be named _anything_ since they’re safely name-spaced inside
“host.internal”.
E.g., you can now have an internal property called “title”, which
doesn’t interfere _at all_ with the inherited property “title”, nor the
inherited attribute “title”.
Closes #74.
> Relax access to internal properties.

- test/test-default-properties.js
- test/test-initial-properties.js
- x-element.js
Previously, we allowed these to be shared across all instances, it’s now
only shared over time across the same instance.
Importantly, the same default value is used per-instance over and over
again. Otherwise, you might unnecessarily cause additional computes when
an upstream dependency gets a _new_ default reference.
IMPORTANTLY, this means that if you wrote code like `default: () => () => (\* whatever *\)`, you need to change it to `default: () => (\* whatever *\)`. Previously, that's how you would make something _per instance_ vs _per constructor_. I.e., whereas the functional syntax served as a reminder that you were setting something mutable, you now just _cannot_ set a mutable default on the constructor _at all_.
> Make functional “initial”/“default” per instance.

- test/test-analysis-errors.js
- test/test-attribute-changed-errors.js
- test/test-basic-properties.js
- x-element.js
There’s been a lot of discussion about the opinions “x-element” makes to
be helpful — and sometimes the accusation is that “x-element” is getting
in the way.
This PR removes _all_ such nudges. This should feel inline with our
choice to remove errors for attempting to access `internal` properties
on the host (e.g., `host.myInternalProp` just returns `undefined` now).
In particular, we no longer error for the following:
* If an attribute is set for an unserializable property — we no longer
observe such attributes at all.
And, we no longer warn for the following:
* If you have a property that shadows the HTMLElement interface’s
prototype chain — e.g., “title”, “draggable”, “role”, “dataset”,
“style”, etc, etc. The assumption is that users of “x-element” are
experts and they would only do …
> Removes all “nudges” from “x-element”.

- test/test-initial-properties.js
When “initial” is provided with a non-literal (compound) value, the
return value should never be shared across other instances of the
element.
Closes #89
> Test “initial” works as expected with non-literal.

- test/test-scratch.js
- x-element.js
> Allow authors to extend “observedAttributes”.

- test/test-listeners.js
- x-element.js
Previously, “initializeHost” was called ahead of “addListeners”. There was an edge case where such depth-first initialization made it possible for synchronous events from children to be emitted before the delegated event listeners had been setup on the parent.
This change ensures the following happens in order on first connection:
1. The host itself is initialized.
2. The static listeners are added.
3. The host undergoes its initial render.
Previously, (2) and (3) were conceptually swapped.
> Setup listeners before initial render.

- test/test-internal-properties.js
- x-element.js
Internal properties should be completely decoupled from the public interface. This change set adds a guard to ensure that we don’t try to lookup the property name on the public interface when upgrading the element.
Closes #129.
> Skip initial lookup for internal properties.

- test/test-template-engine.js
- x-element.js
Characters like “<”, “/”, and “>” are special in html and we use them as boundary markers to determine where we are as we walk through the result of a tagged template literal callback.
However, it’s perfectly allowable to use the characters in the markup itself if they’re quoted. Take the following, resonable example:
```
html`<a href="https://example.com" target="${target}">click me</a>`
```
Previously, because of the “/” characters in the “href” attribute declaration, the “${target}” binding would get missed. This is now fixed to allow quoted, special characters.
> Allow special characters in quoted attributes.

- test/test-template-engine.js
- x-element.js
Eventually, we will support this completely, but not at the cost of performance. The prior solution here encountered catastrophic backtracking due to how it was looking for escaped characters.
> Allow everything but “>” character in template.

- package.json
- test.js
- test/index.js
- test/test-scratch.js
- test/test-template-engine.js
- test/x-test.js
- yarn.lock
Some notes:
* “x-test” comes with grouping features, so that’s leveraged a bit.
* “x-test” now produces TAP 14, so we can bump “tap-parser” as well.
* “puppeteer” bumps from 13.x >> 19.x — fortunately nothing broke us.
> Update dependencies for testing.

- test/test-template-engine.js
- x-element.js
If a user tries to interpolate in “style” or “script” tags, just bail out with a clear error. Previously, we sort of silently replaced the content, which is ultimately harder on developers to debug.
> Throw for sketchy interpolation.

- test/test-computed-properties.js
- x-element.js
This handles a nuanced edge case where internal, computed properties can be incorrect if they were interrogated between host construction and initialization.
For example:
```javascript
// This will trigger construction (assuming the element is defined).
const element = document.createElement('my-element');
// Do things after construction, before initialization.
// This will trigger initialization (again, assuming definition).
document.body.append(element);
// Do things after initialization while connected.
```
This change set should guarantee that after initialization, during connection — things will be correct. We cannot make such guarantees when not connected due to lack of eventing around attribute callbacks.
Closes #143.
> Ensure computation on initialization.

- test/test-basic-properties.js
- x-element.js
It would always be counter-intuitive to declare `<my-element number>` in HTML markup and introspect the element to find `element.number === 0`.
In other words, while it’s true that in JS `Number('') === 0`, this is not sensible behavior when deserializing values in markup into typed objects in JS.
This is mostly due to the concept of so-called “boolean attributes”. As a custom element author, you don’t want to coerce a boolean attribute to a `Number`. In otherwords, when dealing with numbers, the markup `<my-element number>` should _not_ equal `<my-element number="0">`.
While this change makes a strong opinion, part of the goal of `x-element` is to reduce obvious boiler plate. Since it seems incredibly unlikely that any author would actually _desire_ the `Number('') >> 0` behavior, taking …
> Deserialize `""` to `NaN` for `Number` type.

- demo/lit-html/base-element.js
- demo/performance/index.js
- demo/uhtml/base-element.js
In a some places, we demo loading 3rd party dependencies over-the-wire. The latest versions of these dependencies on `unpkg` require a slightly different url. Just a minor change to update those.
> Update import paths for networked demos.

- README.md
- eslint.config.js
- package.json
- server.js
- yarn.lock
> Removes http-server

- package-lock.json
- package.json
- server.js
- test.js
> Fix test runner, smarter server

- x-element.js
Because some template engines can throw _immutable_ errors, it’s safer and better to use an “error cause” to _chain_ the old error to our own versus trying to mutate the original.
Closes #128.
> Leverage error “cause” for wrapping render errors.

- SPEC.md
Small documentation change-- clarifies that computed properties are lazily evaluated. Resolves #178.
> Documentation: Clarify that computed properties are lazy.

- test/test-template-engine.js
- x-element.js
Resolves #179 
Previously, the repeat and map functions were unable to rerender their contents at all unless the reference to the value they're iterating over changed. This change makes it to where, by default, repeat and map will run their template every time the template function renders, and adds a feature for memoizing the output with a cache key function if desired.
This merge request also adds documentation about the limitations of reactively re-rendering based on arrays and other complex data, and details workarounds/strategies for dealing with this.
As one more change, I've added `.nvmrc` to gitignore so that people using it don't pollute the repo. If desired, I could instead add the target npm version to its contents.
**Testing instructions**:
1. Create this element that …
> Fix: Repeat/Map now always rerender.

- CHANGELOG.md
- doc/SPEC.md
- test/index.js
- test/test-render-root.js
- test/test-styles.css.js
- test/test-styles.html
- test/test-styles.js
- x-element.d.ts
- x-element.js
One common pattern for element authors (now that import attributes enable folks to import css files directly) is to adopt imported style sheets into a shadow root at custom element initialization time.
This adds one static getters — `styles`. The goal is to make shadow root initialization as _declarative_ as possible. Note that we still expose `createRenderRoot` so we don’t get in the way if folks need to do something more advanced (it’s also still the only way to forgo the creation of a shadow root at all).
Closes #52.
> Improve style sheet adoption ergonomics.

- doc/TEMPLATE_ENGINE.md
The point of this document is to explain (to folks that are already experts in web development) how html template engines conceptually work.
It walks the reader through a series of iterations which add increasing sophistication to a toy template engine library.
Closes #187.
> Add advanced “TEMPLATE_ENGINE.md” documentation.

- doc/TEMPLATE_ENGINE.md
The handling of the heavy check / heavy cross characters and their styling looked _real bad_ before. I had been developing in VSCode, where the preview looked much different!
> Improve indicators for “TEMPLATE_ENGINE.md” docs.

- doc/TEMPLATES.md
(Re-opened since #190 was forcibly auto-closed by the target merge branch being deleted)
This PR adds documentation on rendering limitations as they pertain to complex data structures. It also makes some minor typographical adjustments found along the way.
cc @theengineear @klebba
> docs: Document re-rendering based on complex data.

- x-element.js
This is now baseline as of 2023 so we ought to be able to use it. We use symbols to prevent internal abstractions from being leaked into code authored by integrators — for that, we just need an opaque token. But, because weak maps previously needed to be keyed with an _object_, we just created a dummy object as our key.
Now, we can take the more modern approach of keying with a symbol.
Closes #192.
> Use non-registered symbols as weak map keys.

- test/test-observed-properties.js
- test/test-template-engine.js
- x-element.js
Currently, we inject dom into our container and then update bindings. This causes all child “connectedCallback” calls to fire _before_ we bind property / attribute / etc. updates.
That’s problematic because elements have no good way to observe initial deltas in the render tree. Said another way…
We used to do this:
1. Create new nodes and inject new nodes into our container.
2. Bind value updates to new nodes.
Now we do this:
1. Create new nodes.
2. Bind value updates to new nodes.
3. Inject new nodes into our container.
Closes #197.
> Perform rendering in a fully  depth-first manner.

- test/test-basic-properties.js
- x-element.js
The default browser behavior when setting `.textContent` to `null` or `undefined` is to ultimately set the content to `''`†. This is quite different from the behavior of `createTextNode` though… by splitting the text node creation into multiple steps we can consistently leverage `.textContent` and remove the need to `?? ''`.
† Note that the WHATWG spec only defines that behavior for `null`, but
in practice all modern browsers seem to treat `undefined` similarly.
Here’s the [spec](https://dom.spec.whatwg.org/#dom-node-textcontent) for reference. This is related to #204.
> Remove nullish coalescing for `textContent`.

- CHANGELOG.md
- demo/lit-html/base-element.js
- demo/lit-html/index.html
- demo/performance/index.css
- demo/performance/index.html
- demo/performance/index.js
- demo/react/index.html
- demo/react/index.js
- demo/uhtml/base-element.js
- demo/uhtml/index.html
- doc/TEMPLATES.md
- eslint.config.js
- test/test-initialization-errors.js
- test/test-template-engine.js
- x-element.js
Changes:
* Adding `??attr` binding syntax.
* Changing `ifDefined` to delete attr on `null` as well as `undefined`.
* Deprecating `ifDefined` / `nullish` in favor of `??attr` binding.
* Deprecating `repeat` in favor of `map`.
* Updating documentation.
Closes #204.
> Prepare for 2.x interface.

- CHANGELOG.md
- test/test-template-engine.js
- x-element.js
Changes:
* Stricter handling of “textarea” binding. Previously we were overly lenient in how the binding worked which caused automagical behavior. For example, newlines were quietly ignored, which could lead to issues if you really _wanted_ newlines in a default value in a text area control and were actually trying to interpolate between lines. Now, it just throws for that case.
* Spec-compliant attribute traversal. Previously, we relied on the browser convention that attributes in a NamedNodeMap would be iterated over in a particular manner. The spec strictly indicates that this is not to be relied on — so we can oblige.
* The deprecated `plaintext` html tag is no longer considered. Use at your own peril…
* General improvements to inline documentation and naming of things.
> Adding a couple minor changes for 2.x interface.

- demo/performance/index.css
- demo/performance/index.html
- demo/performance/index.js
Changes:
* Attempt to test more iterations.
* Do better at right-sizing batches per animation frame.
* Only measure batches to get around security issues with timestamps.
* Show distribution of results for better relative analysis.
> Improve performance tests.

- CHANGELOG.md
- doc/RECIPES.md
- doc/TEMPLATES.md
- test/test-initialization-errors.js
- test/test-template-engine.js
- x-element.js
Additional updates for “2.x” release.
Changes:
* Deprecate `unsafeHTML` and `usafeSVG`.
* Allow binding `DocumentFragment` as a value.
* Tag every line in the “CHANGELOG.md” with an issue ticket.
* Simplified formatting related to bindings in “TEMPLATES.md”.
* Emit deprecation warnings for soon-to-be-gone interfaces.
* Deprecate remaining updaters (e.g., “map”).
* Ditch unecessary “weak maps”.†
* Some performance improvements.
† The search set for the weak maps we’re using gets untenable since it’s
a flat list of pointers for _all_ results. It feels like a reasonable
concession to hang data off of a unique symbol key. These are
non-enumerable (unless specifically trying to enumerate symbols),
which feels internal enough. Additionally, returning the values passed
in by the user doesn’t …
> Additional updates for “2.x” release.

- test/test-template-engine.js
As we investigate whether we ought to do some custom parsing to enhance our ability to provide accurate and clear developer feedback — we want to start back-porting future tests into the current ecosystem so that we don’t miss any interesting cases if / when we update our underlying parsing mechanism.
> Restructure “test-template-engine.js” tests.

- demo/chess/index.js
- demo/index.js
- test/test-computed-properties.js
- test/test-observed-properties.js
- test/test-template-engine.js
- x-template.js
Changes:
* Uses `static get styles()` for demo / test elements. †
* Uses brackets in error messaging — e.g., “<style>” vs “"style"”. ††
†  Inlining style tags will throw a warning in future releases. And, the
suggested usage is to leverage the static `styles` getter.
†† Rather than use quotes when messaging about tag names, it provides
developers better context to see messaging that resembles open tags
so that it’s clear what the error message is all about.
> Updates demo styles and improves error messages.

- test/test-parser.js
- x-parser.js
We need to allow _some_ JS-y escapes that cannot otherwise be accomplished through standard HTML syntax. We had already allowed the backtick and backslash characters — just need the dollar sign as well.
> Allow template interpolation escapes (i.e., “\$”).

- CHANGELOG.md
- test/test-template-engine.js
- ts/x-template.d.ts.map
- x-template.js
Conceptually, if you render `[foo, bar]` and then re-render with just `[bar]` — you don’t expect that the `foo` element will be disconnected and reconnected. However, if we naively first _move_ `bar` to the first slot and then _delete_ `foo`… that‘s exactly what will happen.
Instead, we must first _delete_ `foo` and then _check_ to see if we still need to _move_ `bar`.
Note that if a shuffle is _actually_ necessary, we cannot prevent a disconnect / reconnect from occurring with the current DOM APIs.
Closes #253
> Prevent disconnects on simple re-mappings.

- .github/workflows/publish-to-jsr.yaml
- .github/workflows/publish-to-npm.yaml
- .github/workflows/test.yaml
- package-lock.json
- package.json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference — actually this method depends on Node 22 since 2024
> Update package.json engines again

- CHANGELOG.md
- test/test-template-engine.js
- ts/x-element.d.ts
- ts/x-template.d.ts
- ts/x-template.d.ts.map
- x-element.js
- x-template.js
These aren’t commonly used and developers can simply leverage browser APIs to accomplish these behaviors via `setHTMLUnsafe` and listening to `change` events, respectively.
Closes #208
Closes #216
> Remove “unsafeHTML” and “live” from interface.

- test/forgiving.js
- test/test-template-engine.js
- x-template.js
Just leverage the more modern approach in the handful of places that use this in our code (for decoding character references and in tests).
This feature was baselined in 2024.
> Replaces “innerHTML” with “setHTMLUnsafe”.

- test/forgiving.js
- test/test-parser.js
The default template engine doesn’t allow binding a _literal_ value to a property via the `.` prefix — however, we didn’t previously check this case in our test suite.
Closes #203.
> Adds a test related to literal property bindings.

- package-lock.json
- package.json
- test.js
Previously, the tests weren’t actually being run by GitHub actions for some time now. They would run locally, but the browser would silently fail to launch in GitHub when the action was run.
Additionally, we now “Bail out!” within “test.js” if any exceptions are caught — these are magic words that our TAP parser will recognize and they instruct the parser to immediately consider the test a failure.
> Fixes tests for GitHub actions.

- demo/performance/common.js
- demo/performance/react.js
- test/test-parser.js
Only demo / test changes here — it’s not too hard to support this since most (all?) templating engines will accept a native _array_ as input for a set of children.
> Adds arrays to performance test templates.

- test/test-template-engine.js
- x-template.js
The “repeat” directive is just a shim to create arrays of _entries_. We may remove this from the interface in the future, but we do need it to function as expected in the interim!
Most callers rely on just the first “value” argument, but there’s no good reason not to expose the `(value, index, array)`-triple that a standard callback would receive from “Array.map”.
> Pass standard “Array.map” arguments to “repeat”.

- CHANGELOG.md
- doc/TEMPLATES.md
- test/test-template-engine.js
- ts/x-template.d.ts.map
- x-template.js
Previously, we had a small developer ergonomics guard to throw if an empty document fragment was bound as content. This commit reverts that prior decision for two reasons:
1. The guard checked for “element” children (not “node” children) as we internally use comment node cursors to annotate our DOM. This was too naive as it also doesn’t detect _text nodes_.
2. The guard was misaligned with our philosophy — we don’t want to teach developers how the browser works. I.e., we expect our users to be experts and so we don’t want to inject special decisions which would infer intent and potentially frustrate expert users.
Closes #310.
> Allow binding empty “DocumentFragment” instances.

- CLAUDE.md
- x-template.js
Minor consistency improvement, we use the class name elsewhere for better predictability with private class methods.
> Use “TemplateEngine” versus “this” in “x-element”.
